[build]
  publish = "public"
  command = "yarn run build"
  functions = "./functions"

[build.environment]
  NODE_VERSION = "16.15.1"

[context.production.environment]
  GATSBY_TOKEN_FRONTEND = "https://token.vega.xyz/"
  GATSBY_VEGA_API = "http://nodes-guru.mainnet.vega.community:3008/query"

[context.deploy-preview.environment]
  GATSBY_TOKEN_FRONTEND = "https://token.fairground.wtf/"
  GATSBY_VEGA_API = "https://api.testnet.vega.xyz/graphql"

[functions."send-bug-report"]
  included_files = ["vega-public-key.asc"]
  
[[plugins]]
  package = "@netlify/plugin-sitemap"